---
- name: Please wait and have a coffee!
  hosts: "{{ service_hosts }}"
  gather_facts: yes
  tasks:
    - name: Install mobaxterm
      win_chocolatey:
          name: mobaxterm
          state: present
          ignore_checksums: yes
